#/*Assignment-3
 #*    Team Members
 #* Sai Vamshi Dasari-G01464718
 #* Aryan Sudhagoni-G01454180
 #* Lahari ummadisetty-G01454186
 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: default
  labels:
    app: springboot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-container
        image: saivamshi1432/springboot-app:latest
        ports:
        - containerPort: 8080
