##/*Assignment-3
 #     Team Members
 #Sai Vamshi Dasari-G01464718
 #Aryan Sudhagoni-G01454180
 #Lahari ummadisetty-G01454186
 apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

